<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { type IProduct } from '@/api/models/productsTypes'
import { getProduct } from '@/api/business/products'
import useLoading from '@/features/useLoading'
import ButtonGroup from '@/shared/ui/ButtonGroup.vue'

const { isLoading, setLoading } = useLoading
const { params } = useRoute()

const product = ref<IProduct | null>(null)

onMounted(async () => {
  try {
    setLoading(true)
    product.value = await getProduct(params?.prod_id as string)
    setLoading(false)
  } catch (error) {
    setLoading(false)
    console.log(error)
  }
});
</script>

<template>
  <section class="product">
    <div v-if="!isLoading && product" class="product_card">
      <img class="product_image" :src="product?.imageUrl" :alt="product?.autogeneratedSlug" />
      <section class="right_section">
        <div class="product_info">
          <h3>{{ product?.name }}</h3>
          <h4>Price: {{ product?.price }}₽</h4>
        </div>
        <article class="product_desc" v-html="product?.description"></article>
        <div class="product_group_button">
          <ButtonGroup :id="product?.id" />
        </div>
      </section>
    </div>
    <span v-else>Loading...</span>
  </section>
</template>

<style lang="scss" scoped>
.product {
  display: flex;
  width: 100%;
  justify-content: center;
  align-items: center;
  gap: 40px;
  &_card {
    width: 60%;
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    border: 1px rgb(230, 230, 230) solid;
    padding: 24px;
    border-radius: 12px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    gap: 40px;
  }
  &_info {
    display: flex;
    flex-direction: column;
    gap: 40px;
  }

  &_image {
    width: 60%;
    border-radius: 12px;
  }
  .right_card_section {
    display: flex;
    flex-direction: column;
    align-items: start;
    justify-content: start;
    height: 100%;
    gap: 30px;
  }

  &_description {
    width: 300px;
  }

  &_group_button {
    width: 100%;
  }
}

@media only screen and (max-width: 1350px) {
  .product_info_card {
    flex-direction: column;
  }
}

@media only screen and (max-width: 550px) {
  .product_info_card {
    flex-direction: column;
  }
  .product_info_description {
    max-width: 200px;
  }
}
</style>
