export interface ICategory {
  id: number;
  imageUrl: string;
  name: string;
  url: string;
  autogeneratedSlug: string;
  description: string;
  parentId?: string;
}

export interface ICategoryItems {
  total: number;
  count: number;
  offset: number;
  limit: number;
  items: ICategory[];
}
